#+title: Todo

- more window toggles (fullscreen, logical resolution with letterboxing/pillarboxing, vsync options, show/hide cursor, etc)
  
- move collision data the hell out of glTF - expose a format-agnostic Mesh_Data struct returned by import procs that can be queried by the user to populate collision/AI/navmesh structures themselves

- clean up ui_draw_* functions to be more architecturally similar to the rest of the renderer (might have to rethink coordinate systems...)

- World structure (do not incorporate Actors, requires user-knowledge of multithreading) that associates a single transform.Node with all subsystems that require the concept of 'where an entity is' (spatial grid/collision/spatial audio/etc.), fan-out to those modules in one call instead of user calling a bunch of update_/transform_* in a row

- rewrite main.odin to be a better testbed/demo program to showcase engine's capabilities

- gamepad support via SDL's gamepad facilities (possibly need another API for Web, or limit to desktop-only)
- also on that note, IME input, mouse wheel, etc

- raycasts, raycasts, raycasts.
- also in general Tri_Mesh and regular colliders are two separate worlds, have a user be able to do spatial.move() using arbitrary colliders, not just sphere-trisoup. Have Tri_Mesh work with the collider procs as well (this is a prerequisite for proper spatial.move anyway).
- refactor spatial package to have Spatial structures actually own their colliders. Then just pass transforms to update, don't reshape - if you want a new shape you delete/make again

- more simple rendering primitives - lines, line lists, line strips, wireframes, fill-boxes, collider shapes, etc.

- simple non-shadery postprocessing parameters (logical resolution as mentioned, LUTs, exposure/gamma settings)
- maybe have all these in Screen_Uniforms and separate from Camera_Uniforms

- audio settings (mainly just be able to set volume dynamically)

- some kind of heuristic-based environment probe selection
- planar reflections using existing environment probe machinery

post-1.0 features:

- expose "lib" package which re-imports all functionality so we don't have a dozen imports per project (a 'prelude' to use rust terms)
- optionally use this lib package as an API surface, in order to expose dynamic loading via .dll/.so/whatever.
- once you have dynamic loading, add modding/scripting subsystem

- fix transmission system to be more physically-based, possibly using an SSS map / compute thickness from shadow map (if present)

- implement clustered forward with CPU binning (very cheap win over current forward renderer)

- ktx2 support
  1. parse ktx2 natively in Odin, don't pull in libktx. It's huge.
  2. add zstd decompression on top with the (relatively small) C library
  3. then, only then, pull in basis-universal C++ library and figure out how to build/link it in

- user postprocessing; more involved/stylized shaders like bloom/DoF/motion blur/vignetting/film grain/etc. would have to be written in by users and added as their own pipelines/passes.
- maybe enforce a simple pass/uniform/bind group contract that users can plug their own WGSL into.
- build the pipes, not the water.
