#+title: Todo

- more window toggles (fullscreen, logical resolution with letterboxing/pillarboxing, vsync options, show/hide cursor, etc)
  - borderless fullscreen working, now needs separate logical resolution + framebuffer + output pass. Also do HDR/LDR + color grading here, at a later point
  - cursor lock works on desktop, but needs to be deferred on web somehow
  
- big collision rewrite (spatial2):
  - move collision data the hell out of glTF - expose a format-agnostic Mesh_Data struct returned by import procs that can be queried by the user to populate collision/AI/navmesh structures themselves
  - on that note, separate acceleration structure for Tri_Mesh, expose insert_geometry() or insert_tri_mesh() or something to delineate
  - implement shape tests for each type in spatial2
  - implement shape->triangle tests for arbitrary move() colliders
  - raycasts!!! for each shape
  - orientation for Boxes, transform into local space for shapes & do AABB test, SAT for OBB vs OBB
  - implement Convex Hulls, use SAT you already wrote

- clean up ui_draw_* functions to be more architecturally similar to the rest of the renderer (might have to rethink coordinate systems...)

- World structure (do not incorporate Actors, requires user-knowledge of multithreading) that associates a single transform.Node with all subsystems that require the concept of 'where an entity is' (spatial grid/collision/spatial audio/etc.), fan-out to those modules in one call instead of user calling a bunch of update_/transform_* in a row

- rewrite main.odin to be a better testbed/demo program to showcase engine's capabilities

- gamepad support via SDL's gamepad facilities (possibly need another API for Web, or limit to desktop-only)
- also on that note, IME input, mouse wheel, etc

- more simple rendering primitives - lines, line lists, line strips, wireframes, fill-boxes, collider shapes, etc.

- simple non-shadery postprocessing parameters (logical resolution as mentioned, LUTs, exposure/gamma settings)
- maybe have all these in Screen_Uniforms and separate from Camera_Uniforms
- this should be done AFTER logical resolution, as it should simply operate on the output buffer

- audio settings (mainly just be able to set volume dynamically)

- some kind of heuristic-based environment probe selection so that multiple probes work & background probe fallback comes naturally
- planar reflections using existing environment probe machinery

post-1.0 features:

- expose "lib" package which re-imports all functionality so we don't have a dozen imports per project (a 'prelude' to use rust terms)
- optionally use this lib package as an API surface, in order to expose dynamic loading via .dll/.so/whatever.
- once you have dynamic loading, add modding/scripting subsystem

- fix transmission system to be more physically-based, possibly using an SSS map / compute thickness from shadow map (if present)

- implement clustered forward with CPU binning (very cheap win over current forward renderer)

- ktx2 support
  1. parse ktx2 natively in Odin, don't pull in libktx. It's huge.
  2. add zstd decompression on top with the (relatively small) C library
  3. then, only then, pull in basis-universal C++ library and figure out how to build/link it in

- user postprocessing; more involved/stylized shaders like bloom/DoF/motion blur/vignetting/film grain/etc. would have to be written in by users and added as their own pipelines/passes.
- maybe enforce a simple pass/uniform/bind group contract that users can plug their own WGSL into.
- build the pipes, not the water.
